
min_detection_radius: 5
max_detection_radius: 50

# Mask Options
# r_y_lower: 185
# r_y_upper: 255
# r_cr_lower: 155
# r_cr_upper: 235
# r_cb_lower: 94
# r_cb_upper: 190

# 21
r_y_lower: 5
r_y_upper: 40

# 110,925
r_cr_lower: 90
r_cr_upper: 255

# 239
r_cb_lower: 120
r_cb_upper: 255


# g_y_lower: 0
# g_y_upper: 255

# g_cr_lower: 70
# g_cr_upper: 110

# g_cb_lower: 120
# g_cb_upper: 150


g_y_lower: 65
g_y_upper: 93

g_cr_lower: 80
g_cr_upper: 200

g_cb_lower: 110
g_cb_upper: 255



b_y_lower: 105
b_y_upper: 125

b_cr_lower: 80
b_cr_upper: 180

b_cb_lower: 80
b_cb_upper: 180


# Directly copied from config/<device_id>/calib_color.yaml
cameraMatrix:
   rows: 3
   cols: 3
   dt: d
   data: [ 1.0815577461638704e+03, 0., 9.6726278213157309e+02, 0.,
       1.0781758691523264e+03, 5.4445604167967088e+02, 0., 0., 1. ]