

cropbox_filter/base_frame: kinect2_rgb_optical_frame
cropbox_filter/target_frame: ws_center
cropbox_filter/use_transform: 1
cropbox_filter/x_min: -1
cropbox_filter/x_max: 1
cropbox_filter/y_min: -1
cropbox_filter/y_max: 1
cropbox_filter/z_min: 0.1
cropbox_filter/z_max: 1.5

red_color_filter/use_hsi: 1
red_color_filter/r_min: -20
red_color_filter/r_max: 30
red_color_filter/g_min: 40
red_color_filter/g_max: 255
red_color_filter/b_min: 40
red_color_filter/b_max: 255

green_color_filter/use_hsi: 1
green_color_filter/r_min: 110
green_color_filter/r_max: 130
green_color_filter/g_min: 40
green_color_filter/g_max: 255
green_color_filter/b_min: 40
green_color_filter/b_max: 255

blue_color_filter/use_hsi: 1
blue_color_filter/r_min: 128
blue_color_filter/r_max: 40
blue_color_filter/g_min: 50
blue_color_filter/g_max: 255
blue_color_filter/b_min: 40
blue_color_filter/b_max: 255



# Directly copied from config/<device_id>/calib_color.yaml
cameraMatrix:
   rows: 3
   cols: 3
   dt: d
   data: [ 1.0815577461638704e+03, 0., 9.6726278213157309e+02, 0.,
       1.0781758691523264e+03, 5.4445604167967088e+02, 0., 0., 1. ]